spring.ai.openai.base-url=https://api.xty.app
spring.ai.openai.api-key=sk-Hhk1mg4P1Uo2ND5Zk4G35mgIOJTT7mCjEOI1YMe5IBHPeNSV
spring.ai.openai.chat.options.model=gpt-4
#spring.ai.openai.base-url=https://api.deepseek.com
#spring.ai.openai.api-key=sk-0b470f0099a54b86a200ac30d727e0ee
#spring.ai.openai.chat.options.model=deepseek-chat
#spring.ai.openai.chat.options.model=deepseek-reasoner
# 模型温度
#spring.ai.openai.chat.options.temperature=1.0
# 最大token数
#spring.ai.openai.chat.options.max-tokens=50
# 重复词惩罚
#spring.ai.openai.chat.options.frequency-penalty=0
spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=deepseek-r1:8b
spring.ai.ollama.chat.options.model=qwen2.5:7b
spring.ai.ollama.embedding.model=bge-m3

# 文生图配置
spring.ai.openai.image.base-url=https://api.xty.app
spring.ai.openai.image.api-key=sk-Hhk1mg4P1Uo2ND5Zk4G35mgIOJTT7mCjEOI1YMe5IBHPeNSV
spring.ai.openai.image.options.model=dall-e-3
spring.ai.openai.image.options.size=1024x1024
spring.ai.openai.image.options.quality=hd
spring.ai.openai.image.options.response-format=url

# 文本转语音配置
spring.ai.openai.audio.speech.base-url=https://api.xty.app
spring.ai.openai.audio.speech.api-key=sk-Hhk1mg4P1Uo2ND5Zk4G35mgIOJTT7mCjEOI1YMe5IBHPeNSV
spring.ai.openai.audio.speech.options.model=tts-1
spring.ai.openai.audio.speech.options.voice=alloy
spring.ai.openai.audio.speech.options.response-format=mp3

# 语音转文本配置
spring.ai.openai.audio.transcription.base-url=https://api.xty.app
spring.ai.openai.audio.transcription.api-key=sk-Hhk1mg4P1Uo2ND5Zk4G35mgIOJTT7mCjEOI1YMe5IBHPeNSV
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.response-format=TEXT
spring.ai.openai.audio.transcription.options.language=zh

# MCP客户端配置
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.name=spring-ai-mcp-client
spring.ai.mcp.client.request-timeout=5s
spring.ai.mcp.client.type=sync
spring.ai.mcp.client.sse.connections.storeserver.url=http://localhost:8989
#spring.ai.mcp.client.sse.connections.orderservice.url=http://localhost:9898
